### ISSUE TITLE
Tracking Magic Book To Dos

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#63]
These will eventually become separate issues but just keeping track of some open things that I need to do with the new magic book:
- [x] Table of Contents
- [ ] Index
- [ ] auto-numbering?
- [x] move all `<img alt="">` tags to `<figcaption>`
- [x] math formula
- [x] Code comments and styling
- [ ] HTML JS instead of PNG

**Comment by shiffman** [comment]
Closing this issue and will open individual ones for remaining items like #157
